[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tree-sitter-fountain"
description = "A markup syntax for screenplays."
version = "0.3.3"
keywords = ["incremental", "parsing", "tree-sitter", "fountain"]
classifiers = [
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Compilers",
  "Topic :: Text Processing :: Linguistic",
  "Typing :: Typed",
]
authors = [{ name = "Dr Griffith Rees", email = "info@box3spool5.org" }]
requires-python = ">=3.9"
license.text = "MIT"
readme = "README.md"

[project.urls]
Homepage = "https://github.com/griff-rees/tree-sitter-fountain"

[project.optional-dependencies]
core = ["tree-sitter~=0.25"]

[tool.cibuildwheel]
build = "cp39-*"
build-frontend = "build"
